#include "compiler/backend/backend.hpp"

#include <sstream>
#include <string>
#include <string_view>

namespace breadcrumbs::compiler::backend {
namespace {

[[nodiscard]] std::string indent(std::size_t level) { return std::string(level * 2, ' '); }

[[nodiscard]] std::vector<std::string> namespace_parts(std::string_view fqn) {
    std::vector<std::string> parts;
    std::string current;
    for (char ch : fqn) {
        if (ch == '.') {
            if (!current.empty()) {
                parts.push_back(current);
                current.clear();
            }
            continue;
        }
        current.push_back(ch);
    }
    if (!current.empty()) {
        parts.push_back(current);
    }
    return parts;
}

[[nodiscard]] std::string join_path(const std::vector<std::string>& parts) {
    std::string path;
    for (std::size_t index = 0; index < parts.size(); ++index) {
        if (index > 0) {
            path.push_back('/');
        }
        path.append(parts[index]);
    }
    return path;
}

[[nodiscard]] std::string file_path_for_namespace(const CodegenOptions& options,
                                                  const std::string& namespace_fqn) {
    if (namespace_fqn.empty()) {
        std::string path = options.root_file_stem;
        path.append(options.file_extension);
        if (!options.output_directory.empty()) {
            return options.output_directory + "/" + path;
        }
        return path;
    }

    const std::vector<std::string> parts = namespace_parts(namespace_fqn);
    std::string path = join_path(parts);
    path.append(options.file_extension);
    if (!options.output_directory.empty()) {
        return options.output_directory + "/" + path;
    }
    return path;
}

[[nodiscard]] std::string namespace_comment(std::string_view fqn) {
    if (fqn.empty()) {
        return "// Namespace: <root>\n";
    }
    return "// Namespace: " + std::string(fqn) + "\n";
}

void append_namespace_open(std::ostringstream& stream,
                           const std::vector<std::string>& namespace_stack) {
    for (const std::string& part : namespace_stack) {
        stream << "namespace " << part << " {\n";
    }
    if (!namespace_stack.empty()) {
        stream << '\n';
    }
}

void append_namespace_close(std::ostringstream& stream,
                            const std::vector<std::string>& namespace_stack) {
    for (auto it = namespace_stack.rbegin(); it != namespace_stack.rend(); ++it) {
        stream << "} // namespace " << *it << "\n";
    }
}

[[nodiscard]] std::string render_namespace_file(const ::breadcrumbs::schema_ir::NamespaceIR& ns) {
    std::ostringstream stream;
    stream << "// Generated by Breadcrumbs.\n";
    stream << namespace_comment(ns.fqn());

    const std::vector<std::string> parts = namespace_parts(ns.fqn());
    append_namespace_open(stream, parts);

    for (int index = 0; index < ns.records_size(); ++index) {
        const ::breadcrumbs::schema_ir::RecordIR& record = ns.records(index);
        stream << indent(parts.size()) << "struct " << record.name() << ";\n";
    }

    for (int index = 0; index < ns.enums_size(); ++index) {
        const ::breadcrumbs::schema_ir::EnumIR& enum_ir = ns.enums(index);
        stream << indent(parts.size()) << "enum class " << enum_ir.name() << ";\n";
    }

    if (!ns.records().empty() || !ns.enums().empty()) {
        stream << '\n';
    }

    append_namespace_close(stream, parts);

    std::string output = stream.str();
    if (!output.empty() && output.back() != '\n') {
        output.push_back('\n');
    }
    return output;
}

void collect_namespace_files(const ::breadcrumbs::schema_ir::NamespaceIR& ns,
                             const CodegenOptions& options, CodegenResult& result) {
    if (ns.records_size() > 0 || ns.enums_size() > 0) {
        result.files.push_back(GeneratedFile{
            .path = file_path_for_namespace(options, ns.fqn()),
            .content = render_namespace_file(ns),
        });
    }

    for (int index = 0; index < ns.namespaces_size(); ++index) {
        collect_namespace_files(ns.namespaces(index), options, result);
    }
}

} // namespace

CodegenResult Backend::generate(const schema_ir::SchemaIrModel& schema_ir,
                                const CodegenOptions& options) const {
    CodegenResult result;

    const ::breadcrumbs::schema_ir::NamespaceIR& root = schema_ir.root_namespace();

    collect_namespace_files(root, options, result);
    return result;
}

} // namespace breadcrumbs::compiler::backend
