name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Protobuf
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libprotobuf-dev libabsl-dev libyaml-dev

      - name: Configure
        run: cmake --preset debug

      - name: Build
        run: cmake --build --preset debug --parallel

      - name: Test
        run: ctest --preset debug
